version: '3.3'

services:
  http-products:
    image: dnevsky/http-products
    container_name: http-products
    env_file:
      - .env
    restart: always
    depends_on:
      migrate-postgres:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5001:5001"
      - "8081:8081"

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ../.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:54321"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
    - ../.cache/:/data
    ports:
    - "6379:63798"
    command: redis-server --save 20 1 --loglevel warning --requirepass asdzxc
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  migrate-postgres:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "./migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy


