version: '3.3'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
    - ./.cache/:/data
    ports:
    - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass asdzxc

  migrate-postgres:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "./migrations", "-database", "postgres://postgres:qwerty@postgres:5432/testdb?sslmode=disable", "up"] 