name: CD
run-name: CI runs deploy to server

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - success

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            rm -rf $REPO_NAME
            git clone https://github.com/${{ github.repository }}
            cd $REPO_NAME
            docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }} ${{ vars.REGISTRY }}
            docker pull ${{ vars.REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$REPO_NAME:latest
            docker-compose down
            docker-compose up -d
            
    