name: CD
run-name: CI runs deploy to server

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-actions@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scripts: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }} ${{ secrets.REGISTRY }}
            docker pull ${{ secrets.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/$REPO_NAME:latest
            docker-compose down
            docker-compose up -d
            
    