name: CI
run-name: ${{ github.actor }} runs test & build & push main

on:
  push:
    branches: [main]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  ACTOR: ${{ github.actor }}

jobs:
  test_build_push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: go test ./...

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build image
        run: docker build --file Dockerfile --tag ${{ vars.DOCKER_USERNAME }}/$REPO_NAME:latest .

      - name: Push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/$REPO_NAME:latest

  deploy:
    needs: test_build_push
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            rm -rf $REPO_NAME
            git clone https://github.com/${{ github.repository }}
            cd $REPO_NAME
            docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }} ${{ vars.REGISTRY }}
            docker pull ${{ vars.REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$REPO_NAME:latest
            docker-compose down
            docker-compose up -d




    