name: Dev
run-name: ${{ github.actor }} runs deploy dev
on:
  merge:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test ./...
    