name: Dev
run-name: ${{ github.actor }} runs deploy dev
on:
  push:
    branches: [dev]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test ./...
    