name: Main
run-name: ${{ github.actor }} runs deploy main
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test ./...
  # build:
  #   runs-on: ubuntu-22.04
  #   needs: test
  #   steps:
  #     - name: Extract Version
  #       id: version_step
  #       run: |
  #         echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
  #         echo "##[set-output name=version_tag;]$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}"
  #         echo "##[set-output name=latest_tag;]$GITHUB_REPOSITORY:latest"
  #     - name: Print Version
  #       run: |
  #         echo ${{steps.version_step.outputs.version_tag}}
  #         echo ${{steps.version_step.outputs.latest_tag}}
    